"use client";

import { loader } from "@monaco-editor/react";
import monacoPackage from "monaco-editor/package.json";
import { useWorkspaceStore } from "@/stores/workspace-store";
import { useSnippetStore } from "@/stores/snippet-store";
import type { Theme } from "@/stores/ui-store";

/* eslint-disable @typescript-eslint/no-explicit-any */

// Keep the editor runtime on the same origin as QueryPad. The versioned URL is generated by
// scripts/copy-editor-assets.mjs and can be cached indefinitely. Every Monaco host (the workbench
// editor, notebook cells) imports this module, so the loader is configured before any mount.
loader.config({ paths: { vs: `/monaco/${monacoPackage.version}/vs` } });

export const monacoThemeName = (theme: Theme) => (theme === "dark" ? "qp-dark" : "qp-light");

/** Completion items for the live catalog (tables, columns) and the snippet library. */
export function sqlCompletionItems(monaco: any, model: any, position: any): { suggestions: any[] } {
  const word = model.getWordUntilPosition(position);
  const range = {
    startLineNumber: position.lineNumber,
    endLineNumber: position.lineNumber,
    startColumn: word.startColumn,
    endColumn: word.endColumn,
  };
  const { tables } = useWorkspaceStore.getState();
  const seen = new Set<string>();
  const suggestions: any[] = [];
  for (const t of tables) {
    suggestions.push({
      label: t.name,
      kind: monaco.languages.CompletionItemKind.Struct,
      insertText: t.name,
      detail: `table, ${t.rowCount.toLocaleString()} rows`,
      range,
    });
    for (const c of t.columns) {
      const key = `${c.name}|${c.type}`;
      if (seen.has(key)) continue;
      seen.add(key);
      suggestions.push({
        label: c.name,
        kind: monaco.languages.CompletionItemKind.Field,
        insertText: c.name,
        detail: `${c.type.toLowerCase()} in ${t.name}`,
        range,
      });
    }
  }
  for (const snippet of useSnippetStore.getState().snippets) {
    suggestions.push({
      label: snippet.name,
      kind: monaco.languages.CompletionItemKind.Snippet,
      insertText: snippet.sql,
      detail: `snippet${snippet.folder ? ` · ${snippet.folder}` : ""}`,
      documentation: snippet.description ? `${snippet.description}\n\n${snippet.sql}` : snippet.sql,
      filterText: snippet.name,
      sortText: `~${snippet.name}`,
      range,
    });
  }
  return { suggestions };
}

const REGISTERED = Symbol.for("querypad.sqlCompletion");

/**
 * Register the SQL completion provider once per Monaco instance (its provider registry is
 * global, while editors mount and unmount freely). The marker lives on the `monaco` object so
 * every caller — notebook cells, the workbench editor — shares one registration.
 */
export function registerSqlCompletion(monaco: any): void {
  if (monaco[REGISTERED]) return;
  monaco[REGISTERED] = true;
  monaco.languages.registerCompletionItemProvider("sql", {
    provideCompletionItems: (model: any, position: any) => sqlCompletionItems(monaco, model, position),
  });
}
