"use client";

import { useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";
import { loader } from "@monaco-editor/react";
import monacoPackage from "monaco-editor/package.json";
import { useWorkspaceStore } from "@/stores/workspace-store";
import { useSnippetStore, saveCurrentAsSnippet } from "@/stores/snippet-store";
import { useUiStore } from "@/stores/ui-store";
import { useCollaborationStore } from "@/stores/collaboration-store";
import { registerEditor } from "@/lib/editor-bridge";
import { runActive } from "@/lib/workspace-actions";
import { formatSql } from "./format-sql";
import { defineQueryPadThemes, codeFontFamily } from "@/lib/monaco-theme";

// Keep the editor runtime on the same origin as QueryPad. The versioned URL is
// generated by scripts/copy-editor-assets.mjs and can be cached indefinitely.
loader.config({ paths: { vs: `/monaco/${monacoPackage.version}/vs` } });

const MonacoEditor = dynamic(() => import("@monaco-editor/react"), {
  ssr: false,
  loading: () => (
    <div className="h-full min-h-0 overflow-hidden bg-surface p-3" role="status" aria-label="Loading SQL editor">
      <span className="sr-only">Loading SQL editor…</span>
      <div className="flex animate-pulse gap-3" aria-hidden="true">
        <div className="flex w-7 shrink-0 flex-col items-end gap-3 pt-1">
          {Array.from({ length: 8 }, (_, i) => <span key={i} className="h-2.5 w-3 rounded bg-raised" />)}
        </div>
        <div className="flex flex-1 flex-col gap-3 pt-1">
          <span className="h-2.5 w-[42%] rounded bg-raised" />
          <span className="h-2.5 w-[68%] rounded bg-raised" />
          <span className="h-2.5 w-[54%] rounded bg-raised" />
          <span className="h-2.5 w-[76%] rounded bg-raised" />
          <span className="h-2.5 w-[37%] rounded bg-raised" />
        </div>
      </div>
    </div>
  ),
});

// Completion provider is registered once per page; it always reads current tables.
let completionRegistered = false;

/* eslint-disable @typescript-eslint/no-explicit-any */
export default function QueryEditor() {
  const activeTabId = useWorkspaceStore((s) => s.activeTabId);
  const query = useWorkspaceStore((s) => s.tabs.find((t) => t.id === s.activeTabId)?.query ?? "");
  const updateTab = useWorkspaceStore((s) => s.updateTab);
  const theme = useUiStore((s) => s.theme);
  const roomId = useCollaborationStore((s) => s.roomId);
  // State (not a ref) so the collaboration binding re-runs once the new editor mounts.
  const [editor, setEditor] = useState<any>(null);
  const monacoRef = useRef<any>(null);

  useEffect(() => {
    monacoRef.current?.editor.setTheme(theme === "dark" ? "qp-dark" : "qp-light");
  }, [theme]);

  useEffect(() => () => registerEditor(null), []);

  // Live collaboration: bind the editor model to the tab's shared Y.Text.
  useEffect(() => {
    if (!roomId) return;
    let binding: { destroy(): void } | null = null;
    let cancelled = false;
    (async () => {
      const [{ getYTextForTab, getAwareness }, { MonacoBinding }] = await Promise.all([
        import("@/lib/collaboration/sync"),
        import("y-monaco"),
      ]);
      const yText = getYTextForTab(activeTabId);
      const model = editor?.getModel();
      if (cancelled || !editor || !yText || !model) return;
      binding = new MonacoBinding(yText, model, new Set([editor]), getAwareness());
    })().catch((err) => console.error("Failed to bind editor to room:", err));
    return () => {
      cancelled = true;
      binding?.destroy();
    };
  }, [roomId, activeTabId, editor]);

  const handleMount = (mounted: any, monaco: any) => {
    const editor = mounted;
    setEditor(mounted);
    monacoRef.current = monaco;
    registerEditor(mounted);
    // Cursor position and selection size for the status bar.
    mounted.onDidChangeCursorSelection(() => {
      const sel = mounted.getSelection();
      const model = mounted.getModel();
      if (!sel || !model) return;
      useUiStore.getState().setCursor({
        line: sel.positionLineNumber,
        column: sel.positionColumn,
        selected: sel.isEmpty() ? 0 : model.getValueInRange(sel).length,
      });
    });
    monaco.editor.setTheme(useUiStore.getState().theme === "dark" ? "qp-dark" : "qp-light");

    // Actions read live state through stores, so they never run a stale query.
    editor.addAction({
      id: "querypad.run",
      label: "Run query (selection or all)",
      keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter],
      run: () => runActive(),
    });
    editor.addAction({
      id: "querypad.ai",
      label: "Ask AI to write SQL",
      keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyK],
      run: () => {
        const ui = useUiStore.getState();
        if (ui.aiOpen) ui.closeAi();
        else ui.openAi();
      },
    });
    editor.addAction({
      id: "querypad.snippet",
      label: "Save as snippet (selection or query)",
      keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.KeyS],
      run: () => void saveCurrentAsSnippet(),
    });
    editor.addAction({
      id: "querypad.format",
      label: "Format SQL (selection or query)",
      keybindings: [monaco.KeyMod.Shift | monaco.KeyMod.Alt | monaco.KeyCode.KeyF],
      run: () => void formatSql(),
    });
    editor.addAction({
      id: "querypad.palette",
      label: "QueryPad command palette",
      keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyP],
      run: () => useUiStore.getState().setPaletteOpen(true),
    });

    if (!completionRegistered) {
      completionRegistered = true;
      monaco.languages.registerCompletionItemProvider("sql", {
        provideCompletionItems: (model: any, position: any) => {
          const word = model.getWordUntilPosition(position);
          const range = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn,
          };
          const { tables } = useWorkspaceStore.getState();
          const seen = new Set<string>();
          const suggestions: any[] = [];
          for (const t of tables) {
            suggestions.push({
              label: t.name,
              kind: monaco.languages.CompletionItemKind.Struct,
              insertText: t.name,
              detail: `table, ${t.rowCount.toLocaleString()} rows`,
              range,
            });
            for (const c of t.columns) {
              const key = `${c.name}|${c.type}`;
              if (seen.has(key)) continue;
              seen.add(key);
              suggestions.push({
                label: c.name,
                kind: monaco.languages.CompletionItemKind.Field,
                insertText: c.name,
                detail: `${c.type.toLowerCase()} in ${t.name}`,
                range,
              });
            }
          }
          // Saved snippets complete by name and insert their SQL.
          for (const snippet of useSnippetStore.getState().snippets) {
            suggestions.push({
              label: snippet.name,
              kind: monaco.languages.CompletionItemKind.Snippet,
              insertText: snippet.sql,
              detail: `snippet${snippet.folder ? ` · ${snippet.folder}` : ""}`,
              documentation: snippet.description ? `${snippet.description}\n\n${snippet.sql}` : snippet.sql,
              filterText: snippet.name,
              sortText: `~${snippet.name}`,
              range,
            });
          }
          return { suggestions };
        },
      });
    }
  };

  return (
    <MonacoEditor
      key={activeTabId}
      defaultLanguage="sql"
      value={query}
      onChange={(v) => updateTab(activeTabId, { query: v ?? "" })}
      beforeMount={defineQueryPadThemes}
      onMount={handleMount}
      theme={theme === "dark" ? "qp-dark" : "qp-light"}
      options={{
        minimap: { enabled: false },
        fontSize: 13,
        lineHeight: 21,
        fontFamily: codeFontFamily(),
        fontLigatures: false,
        lineNumbers: "on",
        lineNumbersMinChars: 3,
        scrollBeyondLastLine: false,
        wordWrap: "on",
        padding: { top: 10, bottom: 10 },
        renderLineHighlight: "line",
        overviewRulerLanes: 0,
        hideCursorInOverviewRuler: true,
        scrollbar: { verticalScrollbarSize: 8, horizontalScrollbarSize: 8 },
        automaticLayout: true,
        tabSize: 2,
      }}
    />
  );
}
